const sharp = require('sharp')

sharp('./src/octocat.svg').png().negate().toFile('./output-sharp/octocat-png-negate.png')
sharp('./src/octocat.svg').negate().png().toFile('./output-sharp/octocat-negate-png.png')
sharp('./src/illustrator.svg').png().negate().toFile('./output-sharp/illustrator-png-negate.png')
sharp('./src/illustrator.svg').negate().png().toFile('./output-sharp/illustrator-negate-png.png')
sharp('./src/illustrator-clip.svg').png().negate().toFile('./output-sharp/illustrator-clip-png-negate.png')
sharp('./src/illustrator-clip.svg').negate().png().toFile('./output-sharp/illustrator-clip-negate-png.png')
sharp('./src/imageoptim.svg').png().negate().toFile('./output-sharp/imageoptim-png-negate.png')
sharp('./src/imageoptim.svg').negate().png().toFile('./output-sharp/imageoptim-negate-png.png')
